// <auto-generated />
namespace Social.NetWork.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DateNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202002160951509_DateNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
